### ISSUE TITLE
Is it possible to specify more than one group?

### ISSUE THREAD

**Issue by jeffreytham** [markward/local_autogroup#14]
Mark, this plugin is absolutely brilliant, thanks for the great work!  What would make it even better would be an ability to specify more than one group to be created, for example, specifying "GroupA | GroupB" in the specified field (e.g. Institution) and have the user added to both groups in enrolled courses.  This would be useful for teachers who teach in more than one group.  Would this be possible (or is it already so)?

**Comment by markward** [comment]
Hi Jeff,

You can already put people in multiple groups by simply adding multiple "group sets" and having different data in different fields. 

If you need to be able to arbitrarily define such fields I believe the enhancements described in issue #2 would be a better solution to this.

Thanks

Mark

**Comment by jeffreytham** [comment]
Mark, thanks very much. Could I trouble you to please direct me to instructions for adding group sets? Thanks in advance.

On Tue, Aug 30, 2016 at 4:54 PM, Mark Ward notifications@github.com wrote:
Hi Jeff,

You can already put people in multiple groups by simply adding multiple "group sets" and having different data in different fields.

If you need to be able to arbitrarily define such fields I believe the enhancements described in issue #2 [https://github.com/markward/local_autogroup/issues/2] would be a better solution to this.

Thanks

Mark
