### ISSUE TITLE
Access rights to dirs in the plugin zip package

### ISSUE THREAD

**Issue by mudrd8mz** [markward/local_autogroup#6]
After installing your plugin from the zip submitted to the plugins directory, I ended up with dirs permissions like `drwx-w----` (root, classes, db, lang). Together with how files ownership is set, this prevents the plugin from being installed.
Please make sure the files and dirs in the zip package give the group the `rx` permissions.
In my case, I had to run `chmod -R g=rX autogroup/`

**Comment by markward** [comment]
I believe that should be resolved now, thanks for letting me know :)
